### ISSUE TITLE
It wont load in automode if git-commit package is installed

### ISSUE THREAD

**Issue by muihlinn** [danilshvalov/git-commit-ts-mode#1]
When `git-commit` package (magit dependency)  is used and `global-git-mode` is non-nil it doesn't use this mode unless you customize `git-commit-major-mode`, which by default is `text-mode`. This had me a while scratching my head.

From git-commit  package description

> When 'global-git-commit-mode' is enabled, which it is by default,
> then opening such a file causes the features described below, to
> be enabled in that buffer.  Normally this would be done using a
> major-mode but to allow the use of any major-mode, as the user sees
> fit, it is done here by running a setup function, which among other
> things turns on the preferred major-mode, by default 'text-mode'.

**Comment by danilshvalov** [comment]
Hi! Thank you very much! I added this to the README. If you think that this is not enough, please write to me about it. Maybe it would be better to do it in some other way.
